name: Tests

# Tests runs unit tests
# This workflow is run on pushed to [develop* master*] and every Pull Requeset where a .go, .mod, .sum have been changed

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-arch: ["amd64", "arm",  "arm64"]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3.3.1
        with:
          go-version: 1.18


      - name: Build
        run: GOARCH=${{matrix.go-arch}} make build


  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3.3.1
        with:
          go-version: 1.18
      - name: tests
        run:  make test
